INSERT INTO USERS (NAME, SURNAME) VALUES ('Kraft', 'Marcus');
INSERT INTO USERS (NAME, SURNAME) VALUES ('Müller', 'Stephanie');
INSERT INTO USERS (NAME, SURNAME) VALUES ('Mustermann', 'Max');

INSERT INTO CATEGORY (NAME) VALUES ('Miete');
INSERT INTO CATEGORY (NAME) VALUES ('Nebenkosten');
INSERT INTO CATEGORY (NAME) VALUES ('Lebensmittel');
INSERT INTO CATEGORY (NAME) VALUES ('Sonstiges');

INSERT INTO BANKACCOUNT (NAME, BANKNAME, IBAN, BIC, USER_ID) VALUES ('Giro', 'Stadtsparkasse Magdeburg', '5478542579', 'DE15478214551485HWJ', '0');

INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_ID, USER_ID, CATEGORY_ID, "DATE") VALUES ('Butter', '0', '0', '2', '2016-01-02');