INSERT INTO USERS (NAME, SURNAME) VALUES ('Kraft', 'Marcus');
INSERT INTO USERS (NAME, SURNAME) VALUES ('Müller', 'Stephanie');
INSERT INTO USERS (NAME, SURNAME) VALUES ('Mustermann', 'Max');

INSERT INTO CATEGORY (NAME) VALUES ('Miete');
INSERT INTO CATEGORY (NAME) VALUES ('Nebenkosten');
INSERT INTO CATEGORY (NAME) VALUES ('Lebensmittel');
INSERT INTO CATEGORY (NAME) VALUES ('Sonstiges');

INSERT INTO BANKACCOUNT_CATEGORY (NAME, IS_REAL_ACCOUNT) VALUES ('Girokonto', 'true');
INSERT INTO BANKACCOUNT_CATEGORY (NAME, IS_REAL_ACCOUNT) VALUES ('Sparkonto', 'true');

INSERT INTO BANKACCOUNT (NAME, BANKNAME, IBAN, BIC, USER_ID, BANKACCOUNT_CATEGORY_NAME) 
VALUES ('Giro', 'Stadtsparkasse Magdeburg', '5478542579', 'DE15478214551485HWJ', '1', 'Girokonto');
INSERT INTO BANKACCOUNT (NAME, BANKNAME, IBAN, BIC, USER_ID, BANKACCOUNT_CATEGORY_NAME) 
VALUES ('Giro2', 'Stadtsparkasse Magdeburg', 'gerhretwsh', 'g5hwhwhwh', '1', 'Girokonto');

INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Butter', 'Giro', '1.25', '1', 'Lebensmittel', '2016-11-02');
INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Kekese', 'Giro', '2.25', '1', 'Lebensmittel', '2016-11-03');
INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Butter2', 'Giro2', '1.45', '1', 'Lebensmittel', '2016-11-02');
INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Kekese2', 'Giro2', '2.75', '1', 'Lebensmittel', '2016-11-03');