INSERT INTO USERS (NAME, SURNAME) VALUES ('Kraft', 'Marcus');
INSERT INTO USERS (NAME, SURNAME) VALUES ('Müller', 'Stephanie');
INSERT INTO USERS (NAME, SURNAME) VALUES ('Mustermann', 'Max');

INSERT INTO CATEGORY (NAME) VALUES ('Miete');
INSERT INTO CATEGORY (NAME) VALUES ('Nebenkosten');
INSERT INTO CATEGORY (NAME) VALUES ('Lebensmittel');
INSERT INTO CATEGORY (NAME) VALUES ('Sonstiges');

INSERT INTO BANKACCOUNT_CATEGORY (NAME, IS_REAL_ACCOUNT) VALUES ('Girokonto', 'true');
INSERT INTO BANKACCOUNT_CATEGORY (NAME, IS_REAL_ACCOUNT) VALUES ('Sparkonto', 'true');

INSERT INTO BANKACCOUNT (NAME, BANKNAME, IBAN, BIC, USER_ID, BANKACCOUNT_CATEGORY_NAME, STARTBUDGET, DATE_STARTBUDGET) 
VALUES ('Giro', 'Stadtsparkasse Magdeburg', '5478542579', 'DE15478214551485HWJ', 1, 'Girokonto', 457.14, '2016-11-01');
INSERT INTO BANKACCOUNT (NAME, BANKNAME, IBAN, BIC, USER_ID, BANKACCOUNT_CATEGORY_NAME, STARTBUDGET, DATE_STARTBUDGET) 
VALUES ('Giro2', 'Stadtsparkasse Magdeburg', 'gerhretwsh', 'g5hwhwhwh', 1, 'Girokonto', 4125.47, '2016-10-01');

INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Butter', 'Giro', 1.25, 1, 'Lebensmittel', '2016-11-02')
INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Kekse', 'Giro', 2.25, 1, 'Lebensmittel', '2016-11-03')
INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Far Cry', 'Giro2', -59.99, 1, 'Sonstiges', '2016-11-02')
INSERT INTO TRANSACTIONS (NAME, BANKACCOUNT_NAME, AMOUNT, USER_ID, CATEGORY_NAME, "DATE") VALUES ('Kekse', 'Giro2', 2.75, 1, 'Lebensmittel', '2016-11-03')